import { ArtistTypes } from '@core/models/artist-types.model';

export enum EditArtistTab {
  Main = 'main',
  Contacts = 'contacts',
  Links = 'links',
  Prices = 'prices',
  Covers = 'covers',
  Photo = 'photo',
  Video = 'video'
}

export enum EditableArtistField {
  Name = 0,
  Description,
  City,
  MusicGenres,
  DanceGenres,
  Covers,
  Links,
  Videos,
  ProfileImage,
  Images,
  Email,
  Phone,
  OneShowPrice,
  Prices
}

export interface EditableArtistFieldMeta {
  required: boolean;
}

export const ARTIST_TYPE_TO_FIELD: {[type: string]: {[field: number]: EditableArtistFieldMeta}} = {
  [ArtistTypes.LiveMusic]: {
    [EditableArtistField.Name]: {required: true},
    [EditableArtistField.Description]: {required: false},
    [EditableArtistField.City]: {required: true},
    [EditableArtistField.MusicGenres]: {required: true},
    [EditableArtistField.DanceGenres]: null,
    [EditableArtistField.Covers]: {required: false},
    [EditableArtistField.Links]: {required: false},
    [EditableArtistField.Videos]: {required: true},
    [EditableArtistField.ProfileImage]: {required: true},
    [EditableArtistField.Images]: {required: false},
    [EditableArtistField.Email]: {required: false},
    [EditableArtistField.Phone]:  {required: false},
    [EditableArtistField.OneShowPrice]: {required: true},
    [EditableArtistField.Prices]: {required: false},
  },
  [ArtistTypes.DJ]: {
    [EditableArtistField.Name]: {required: true},
    [EditableArtistField.Description]: {required: false},
    [EditableArtistField.City]: {required: true},
    [EditableArtistField.MusicGenres]: {required: true},
    [EditableArtistField.DanceGenres]: null,
    [EditableArtistField.Covers]: null,
    [EditableArtistField.Links]: {required: false},
    [EditableArtistField.Videos]: {required: true},
    [EditableArtistField.ProfileImage]: {required: true},
    [EditableArtistField.Images]: {required: false},
    [EditableArtistField.Email]: {required: false},
    [EditableArtistField.Phone]:  {required: false},
    [EditableArtistField.OneShowPrice]: {required: true},
    [EditableArtistField.Prices]: {required: false},
  },
  [ArtistTypes.MC]: {
    [EditableArtistField.Name]: {required: true},
    [EditableArtistField.Description]: {required: false},
    [EditableArtistField.City]: {required: true},
    [EditableArtistField.MusicGenres]: null,
    [EditableArtistField.DanceGenres]: null,
    [EditableArtistField.Covers]: null,
    [EditableArtistField.Links]: {required: false},
    [EditableArtistField.Videos]: {required: true},
    [EditableArtistField.ProfileImage]: {required: true},
    [EditableArtistField.Images]: {required: false},
    [EditableArtistField.Email]: {required: false},
    [EditableArtistField.Phone]:  {required: false},
    [EditableArtistField.OneShowPrice]: {required: true},
    [EditableArtistField.Prices]: {required: false},
  },
  [ArtistTypes.DanceShow]: {
    [EditableArtistField.Name]: {required: true},
    [EditableArtistField.Description]: {required: false},
    [EditableArtistField.City]: {required: true},
    [EditableArtistField.MusicGenres]: null,
    [EditableArtistField.DanceGenres]: {required: true},
    [EditableArtistField.Covers]: null,
    [EditableArtistField.Links]: {required: false},
    [EditableArtistField.Videos]: {required: true},
    [EditableArtistField.ProfileImage]: {required: true},
    [EditableArtistField.Images]: {required: false},
    [EditableArtistField.Email]: {required: false},
    [EditableArtistField.Phone]:  {required: false},
    [EditableArtistField.OneShowPrice]: {required: true},
    [EditableArtistField.Prices]: {required: false},
  },
  [ArtistTypes.StandUp]: {
    [EditableArtistField.Name]: {required: true},
    [EditableArtistField.Description]: {required: false},
    [EditableArtistField.City]: {required: true},
    [EditableArtistField.MusicGenres]: null,
    [EditableArtistField.DanceGenres]: null,
    [EditableArtistField.Covers]: null,
    [EditableArtistField.Links]: {required: false},
    [EditableArtistField.Videos]: {required: true},
    [EditableArtistField.ProfileImage]: {required: true},
    [EditableArtistField.Images]: {required: false},
    [EditableArtistField.Email]: {required: false},
    [EditableArtistField.Phone]:  {required: false},
    [EditableArtistField.OneShowPrice]: {required: true},
    [EditableArtistField.Prices]: {required: false},
  },
  [ArtistTypes.Other]: {
    [EditableArtistField.Name]: {required: true},
    [EditableArtistField.Description]: {required: false},
    [EditableArtistField.City]: {required: true},
    [EditableArtistField.MusicGenres]: null,
    [EditableArtistField.DanceGenres]: null,
    [EditableArtistField.Covers]: null,
    [EditableArtistField.Links]: {required: false},
    [EditableArtistField.Videos]: {required: true},
    [EditableArtistField.ProfileImage]: {required: true},
    [EditableArtistField.Images]: {required: false},
    [EditableArtistField.Email]: {required: false},
    [EditableArtistField.Phone]:  {required: false},
    [EditableArtistField.OneShowPrice]: {required: true},
    [EditableArtistField.Prices]: {required: false},
  },
}

export const ARTIST_TYPE_TO_TAB: {[type: string]: EditArtistTab[]} = {
  [ArtistTypes.LiveMusic]: [
    EditArtistTab.Main,
    EditArtistTab.Photo,
    EditArtistTab.Video,
    EditArtistTab.Prices,
    EditArtistTab.Contacts,
    EditArtistTab.Links,
    EditArtistTab.Covers,
  ],
  [ArtistTypes.DJ]: [
    EditArtistTab.Main,
    EditArtistTab.Photo,
    EditArtistTab.Video,
    EditArtistTab.Prices,
    EditArtistTab.Contacts,
    EditArtistTab.Links,
  ],
  [ArtistTypes.MC]: [
    EditArtistTab.Main,
    EditArtistTab.Photo,
    EditArtistTab.Video,
    EditArtistTab.Prices,
    EditArtistTab.Contacts,
    EditArtistTab.Links,
  ],
  [ArtistTypes.DanceShow]: [
    EditArtistTab.Main,
    EditArtistTab.Photo,
    EditArtistTab.Video,
    EditArtistTab.Prices,
    EditArtistTab.Contacts,
    EditArtistTab.Links,
  ],
  [ArtistTypes.StandUp]: [
    EditArtistTab.Main,
    EditArtistTab.Photo,
    EditArtistTab.Video,
    EditArtistTab.Prices,
    EditArtistTab.Contacts,
    EditArtistTab.Links,
  ],
  [ArtistTypes.Other]: [
    EditArtistTab.Main,
    EditArtistTab.Photo,
    EditArtistTab.Video,
    EditArtistTab.Prices,
    EditArtistTab.Contacts,
    EditArtistTab.Links,
  ],
}
